spring:
  datasource:
    url: jdbc:postgresql://db.telco-client-001.com:5432/orchestrix
    username: ${DB_USER:orchestrix}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
    
orchestrix:
  runtime:
    mode: production
    client-id: telco-client-001
  
  images:
    base-path: /opt/orchestrix/images
  
  deployments:
    base-path: /opt/deployments/telco-client-001
  
  repository:
    type: google-drive
    google-drive:
      folder-id: 1A2B3C4D5E6F7G8H9I0J
      credentials-path: /opt/orchestrix/credentials/google-drive.json
    
vault:
  enabled: true
  url: https://vault.telco-client-001.com
  token: ${VAULT_TOKEN}
  
logging:
  level:
    com.telcobright.orchestrix.clarity: INFO
  file:
    name: /var/log/orchestrix/application.log