spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orchestrix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    
orchestrix:
  runtime:
    mode: local
  
  images:
    base-path: ./images
  
  deployments:
    base-path: ./deployments/debug-local
  
  repository:
    type: local-filesystem
    path: ./images
    
vault:
  enabled: false
  mock: true
  
logging:
  level:
    com.telcobright.orchestrix.clarity: DEBUG