spring:
  application:
    name: orchestrix
  
  profiles:
    active: ${ORCHESTRIX_PROFILE:dev}
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

server:
  port: 8080
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:30m}

# CORS Configuration  
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3010}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:orchestrix-secret-key-for-jwt-token-generation-must-be-at-least-256-bits}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always