package com.telcobright.orchestrix.automation.routing.wireguard;

import com.telcobright.orchestrix.automation.routing.NetworkingGuidelineHelper;
import com.telcobright.orchestrix.automation.routing.NetworkingGuidelineHelper.NodeNetworkConfig;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates WireGuard overlay network configurations per TelcoBright networking guideline.
 *
 * Handles:
 * - Mesh peer configuration with correct AllowedIPs (/32 for overlay, /24 for containers)
 * - VPN gateway vs mesh-only node distinction
 * - Private/public key generation using wg genkey/pubkey
 * - Configuration file generation for wg-overlay interface
 *
 * Critical: Uses /32 for mesh peer overlay IPs to prevent routing conflicts!
 *
 * @author TelcoBright Orchestrix Team
 * @since 2025-11-10
 */
public class WireGuardConfigGenerator {

    /**
     * Represents a WireGuard key pair (private + public)
     */
    public record KeyPair(String privateKey, String publicKey) {}

    /**
     * Represents a mesh peer node configuration
     */
    public record MeshPeer(
        String hostname,
        String managementIp,
        String overlayIp,
        String publicKey,
        String containerSubnet,
        boolean isVpnGateway
    ) {}

    /**
     * Represents a VPN client configuration
     */
    public record VpnClient(
        String name,
        String clientIp,
        String publicKey
    ) {}

    /**
     * Generates a WireGuard private/public key pair using wg command.
     *
     * @return KeyPair with generated keys
     * @throws RuntimeException if key generation fails
     */
    public static KeyPair generateKeyPair() {
        try {
            // Generate private key
            Process privateKeyProcess = new ProcessBuilder("wg", "genkey")
                .redirectErrorStream(true)
                .start();

            BufferedReader privateReader = new BufferedReader(
                new InputStreamReader(privateKeyProcess.getInputStream())
            );
            String privateKey = privateReader.readLine().trim();
            privateKeyProcess.waitFor();

            if (privateKey.isEmpty()) {
                throw new RuntimeException("Failed to generate private key");
            }

            // Generate public key from private key
            Process publicKeyProcess = new ProcessBuilder("wg", "pubkey")
                .redirectErrorStream(true)
                .start();

            publicKeyProcess.getOutputStream().write((privateKey + "\n").getBytes());
            publicKeyProcess.getOutputStream().flush();
            publicKeyProcess.getOutputStream().close();

            BufferedReader publicReader = new BufferedReader(
                new InputStreamReader(publicKeyProcess.getInputStream())
            );
            String publicKey = publicReader.readLine().trim();
            publicKeyProcess.waitFor();

            if (publicKey.isEmpty()) {
                throw new RuntimeException("Failed to generate public key");
            }

            return new KeyPair(privateKey, publicKey);

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate WireGuard key pair: " + e.getMessage(), e);
        }
    }

    /**
     * Generates WireGuard overlay configuration for a mesh peer node.
     *
     * @param thisNode Current node configuration
     * @param privateKey Private key for this node
     * @param meshPeers List of all mesh peers (excluding this node)
     * @param vpnClients List of VPN clients (empty if not VPN gateway)
     * @param isVpnGateway Whether this node accepts VPN clients
     * @return Complete wg-overlay.conf content
     */
    public static String generateOverlayConfig(
        NodeNetworkConfig thisNode,
        String privateKey,
        List<MeshPeer> meshPeers,
        List<VpnClient> vpnClients,
        boolean isVpnGateway
    ) {
        StringBuilder config = new StringBuilder();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);

        // Header
        config.append("# WireGuard Overlay Configuration\n");
        config.append("# Generated by Orchestrix automation\n");
        config.append("# Generated: ").append(timestamp).append("\n");
        config.append("# Node: ").append(thisNode.hostname()).append("\n");
        config.append("# Overlay IP: ").append(thisNode.overlayIp()).append("\n");
        config.append("# Container Subnet: ").append(thisNode.containerSubnet()).append("\n");

        String role = isVpnGateway ? "BGP mesh peer + VPN Gateway" : "BGP mesh peer only";
        config.append("# Role: ").append(role).append("\n\n");

        // Interface section
        config.append("[Interface]\n");
        config.append("Address = ").append(thisNode.overlayIpWithCidr()).append("\n");
        config.append("ListenPort = ").append(thisNode.overlayPort()).append("\n");
        config.append("PrivateKey = ").append(privateKey).append("\n\n");

        // BGP Mesh Peers
        config.append("# ===== BGP Mesh Peers =====\n\n");
        for (MeshPeer peer : meshPeers) {
            config.append("# Peer: ").append(peer.hostname())
                  .append(" (").append(peer.managementIp()).append(")\n");

            if (peer.isVpnGateway()) {
                config.append("# VPN Gateway - must allow VPN client traffic\n");
            }

            config.append("[Peer]\n");
            config.append("PublicKey = ").append(peer.publicKey()).append("\n");
            config.append("Endpoint = ").append(peer.managementIp()).append(":")
                  .append(NetworkingGuidelineHelper.getOverlayListenPort()).append("\n");

            // CRITICAL: Use /32 for peer overlay IP, not /24!
            // If peer is VPN gateway, also allow VPN client range
            if (peer.isVpnGateway()) {
                config.append("AllowedIPs = ").append(peer.overlayIp()).append("/32, ")
                      .append(NetworkingGuidelineHelper.getVpnClientRange()).append(", ")
                      .append(peer.containerSubnet()).append("\n");
            } else {
                config.append("AllowedIPs = ").append(peer.overlayIp()).append("/32, ")
                      .append(peer.containerSubnet()).append("\n");
            }

            config.append("PersistentKeepalive = 25\n\n");
        }

        // VPN Clients (only if this is VPN gateway)
        if (isVpnGateway && !vpnClients.isEmpty()) {
            config.append("# ===== VPN Clients =====\n");
            config.append("# Developer VPN access - connects ONLY to this node\n\n");

            for (VpnClient client : vpnClients) {
                config.append("# VPN Client: ").append(client.name())
                      .append(" (").append(client.clientIp()).append(")\n");
                config.append("[Peer]\n");
                config.append("PublicKey = ").append(client.publicKey()).append("\n");
                config.append("AllowedIPs = ").append(client.clientIp()).append("/32\n\n");
            }
        }

        return config.toString();
    }

    /**
     * Generates VPN client configuration file.
     *
     * @param clientNumber Client number (1-10)
     * @param privateKey Client's private key
     * @param gatewayNode VPN gateway node configuration
     * @param gatewayPublicKey Gateway's public key
     * @return Complete client WireGuard configuration
     */
    public static String generateVpnClientConfig(
        int clientNumber,
        String privateKey,
        NodeNetworkConfig gatewayNode,
        String gatewayPublicKey
    ) {
        StringBuilder config = new StringBuilder();
        String clientIp = NetworkingGuidelineHelper.calculateVpnClientIp(clientNumber);

        config.append("[Interface]\n");
        config.append("Address = ").append(clientIp).append("/32\n");
        config.append("PrivateKey = ").append(privateKey).append("\n");
        config.append("# DNS = 8.8.8.8  # Commented out to prevent DNS override issues\n\n");

        config.append("# Disable local lxdbr0 to avoid routing conflicts with remote network\n");
        config.append("PostUp = ip link set lxdbr0 down 2>/dev/null || true\n");
        config.append("PostDown = ip link set lxdbr0 up 2>/dev/null || true\n\n");

        config.append("[Peer]\n");
        config.append("PublicKey = ").append(gatewayPublicKey).append("\n");
        config.append("Endpoint = ").append(gatewayNode.managementIp()).append(":")
              .append(gatewayNode.overlayPort()).append("\n");
        config.append("AllowedIPs = 10.9.9.0/24, 10.10.0.0/16\n");
        config.append("PersistentKeepalive = 25\n");

        return config.toString();
    }

    // Example usage
    public static void main(String[] args) {
        System.out.println("=== WireGuard Config Generator - Example ===\n");

        // Generate keys for 3 nodes
        System.out.println("Generating keys for 3-node cluster...\n");
        KeyPair node1Keys = generateKeyPair();
        KeyPair node2Keys = generateKeyPair();
        KeyPair node3Keys = generateKeyPair();

        // Create node configurations
        NodeNetworkConfig node1 = NetworkingGuidelineHelper.createNodeConfig(1, "node1", "10.255.246.173", 22);
        NodeNetworkConfig node2 = NetworkingGuidelineHelper.createNodeConfig(2, "node2", "10.255.246.174", 22);
        NodeNetworkConfig node3 = NetworkingGuidelineHelper.createNodeConfig(3, "node3", "10.255.246.175", 22);

        // Node 3 is VPN gateway
        boolean node3IsVpnGateway = true;

        // Generate mesh peer lists (each node's perspective)
        List<MeshPeer> node1Peers = List.of(
            new MeshPeer("node2", "10.255.246.174", "10.9.9.2", node2Keys.publicKey(), "10.10.198.0/24", false),
            new MeshPeer("node3", "10.255.246.175", "10.9.9.3", node3Keys.publicKey(), "10.10.197.0/24", true)
        );

        // Generate VPN client
        KeyPair clientKeys = generateKeyPair();
        List<VpnClient> vpnClients = List.of(
            new VpnClient("client1", NetworkingGuidelineHelper.calculateVpnClientIp(1), clientKeys.publicKey())
        );

        // Generate Node 1 config (mesh only)
        System.out.println("=== Node 1 WireGuard Config (Mesh Only) ===");
        String node1Config = generateOverlayConfig(node1, node1Keys.privateKey(), node1Peers, List.of(), false);
        System.out.println(node1Config);

        // Generate VPN client config
        System.out.println("\n=== VPN Client 1 Config ===");
        String clientConfig = generateVpnClientConfig(1, clientKeys.privateKey(), node3, node3Keys.publicKey());
        System.out.println(clientConfig);

        System.out.println("\n✓ Configuration generation complete!");
    }
}
