global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'orchestrix-monitor'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  # Node Exporter - Host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'orchestrix-host'

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          instance: 'loki'

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          instance: 'grafana'

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
        labels:
          instance: 'tempo'

  # LXC containers metrics (if exported)
  - job_name: 'lxc-containers'
    static_configs:
      - targets: []  # Add container exporters here
        labels:
          container_type: 'lxc'

  # Orchestrix application metrics
  - job_name: 'orchestrix-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: []  # Add Orchestrix app endpoints here
        labels:
          app: 'orchestrix'

  # Docker containers via cAdvisor (optional)
  - job_name: 'cadvisor'
    static_configs:
      - targets: []  # Add cAdvisor endpoint if deployed
        labels:
          instance: 'cadvisor'