# Grafana-Loki Production Deployment Configuration
# Version: 1.0
# Target: 10.255.246.175

ssh:
  host: 10.255.246.175
  port: 22
  username: bdcom
  password: ReBJxyd3kGDFW5Cm
  useKey: false

container:
  name: grafana-loki-prod
  version: 1.0.0
  baseImage: images:debian/12

storage:
  provider: btrfs
  path: /home/telcobright/btrfs
  quota: 30G
  useLoopDevice: true
  loopDeviceSize: 50G
  loopDeviceImage: /opt/btrfs-logger.img
  monitoring:
    enabled: true
    rotationThreshold: 80
    forceCleanupThreshold: 90
    checkInterval: 300

versions:
  grafana: "10.2.3"
  loki: "2.9.4"
  promtail: "2.9.4"
  debian: bookworm

ports:
  grafana: 3000
  loki: 3100
  promtail: 9080

network:
  bridge: lxdbr0
  staticIP:

resources:
  memory: 2GB
  cpu: 2

deployment:
  autoRollback: true
  skipValidation: false
  interactive: false
  buildTimeout: 600
  launchTimeout: 120
  containerPath: images/containers/lxc/grafana-loki

validation:
  requiredServices:
    - grafana-server
    - loki
    - promtail
  requiredPorts:
    - 3000
    - 3100
    - 9080
  healthChecks:
    - name: grafana
      url: http://localhost:3000/api/health
      timeout: 10
    - name: loki
      url: http://localhost:3100/ready
      timeout: 10

logging:
  rotation:
    enabled: true
    period: 168h
    deleteDelay: 2h
    compactor: true
    maxLogSize: 100MB

advanced:
  buildScript: images/containers/lxc/grafana-loki/build/build.sh
  transferScripts: false
